// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the alibaba family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// QvqMax is the QVQ Max model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var QvqMax = models.Spec{
	Name:            "qvq-max",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// QwenFlash is the Qwen Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var QwenFlash = models.Spec{
	Name:            "qwen-flash",
	Window:          1000000,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// QwenMax is the Qwen Max model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenMax = models.Spec{
	Name:            "qwen-max",
	Window:          32768,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenMtPlus is the Qwen-MT Plus model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenMtPlus = models.Spec{
	Name:            "qwen-mt-plus",
	Window:          16384,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenMtTurbo is the Qwen-MT Turbo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenMtTurbo = models.Spec{
	Name:            "qwen-mt-turbo",
	Window:          16384,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenOmniTurbo is the Qwen-Omni Turbo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenOmniTurbo = models.Spec{
	Name:            "qwen-omni-turbo",
	Window:          32768,
	MaxOutputTokens: 2048,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenOmniTurboRealtime is the Qwen-Omni Turbo Realtime model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenOmniTurboRealtime = models.Spec{
	Name:            "qwen-omni-turbo-realtime",
	Window:          32768,
	MaxOutputTokens: 2048,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenPlus is the Qwen Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var QwenPlus = models.Spec{
	Name:            "qwen-plus",
	Window:          1000000,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// QwenPlusCharacterJa is the Qwen Plus Character (Japanese) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenPlusCharacterJa = models.Spec{
	Name:            "qwen-plus-character-ja",
	Window:          8192,
	MaxOutputTokens: 512,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenTurbo is the Qwen Turbo model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var QwenTurbo = models.Spec{
	Name:            "qwen-turbo",
	Window:          1000000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// QwenVlMax is the Qwen-VL Max model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenVlMax = models.Spec{
	Name:            "qwen-vl-max",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenVlOcr is the Qwen-VL OCR model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenVlOcr = models.Spec{
	Name:            "qwen-vl-ocr",
	Window:          34096,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// QwenVlPlus is the Qwen-VL Plus model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var QwenVlPlus = models.Spec{
	Name:            "qwen-vl-plus",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen2514bInstruct is the Qwen2.5 14B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen2514bInstruct = models.Spec{
	Name:            "qwen2-5-14b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen2532bInstruct is the Qwen2.5 32B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen2532bInstruct = models.Spec{
	Name:            "qwen2-5-32b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen2572bInstruct is the Qwen2.5 72B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen2572bInstruct = models.Spec{
	Name:            "qwen2-5-72b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen257bInstruct is the Qwen2.5 7B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen257bInstruct = models.Spec{
	Name:            "qwen2-5-7b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen25Omni7b is the Qwen2.5-Omni 7B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen25Omni7b = models.Spec{
	Name:            "qwen2-5-omni-7b",
	Window:          32768,
	MaxOutputTokens: 2048,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen25Vl72bInstruct is the Qwen2.5-VL 72B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen25Vl72bInstruct = models.Spec{
	Name:            "qwen2-5-vl-72b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen25Vl7bInstruct is the Qwen2.5-VL 7B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen25Vl7bInstruct = models.Spec{
	Name:            "qwen2-5-vl-7b-instruct",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen314b is the Qwen3 14B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen314b = models.Spec{
	Name:            "qwen3-14b",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3235bA22b is the Qwen3 235B-A22B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3235bA22b = models.Spec{
	Name:            "qwen3-235b-a22b",
	Window:          131072,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen332b is the Qwen3 32B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen332b = models.Spec{
	Name:            "qwen3-32b",
	Window:          131072,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen38b is the Qwen3 8B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen38b = models.Spec{
	Name:            "qwen3-8b",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3AsrFlash is the Qwen3-ASR Flash model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3AsrFlash = models.Spec{
	Name:            "qwen3-asr-flash",
	Window:          53248,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Coder30bA3bInstruct is the Qwen3-Coder 30B-A3B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3Coder30bA3bInstruct = models.Spec{
	Name:            "qwen3-coder-30b-a3b-instruct",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Coder480bA35bInstruct is the Qwen3-Coder 480B-A35B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3Coder480bA35bInstruct = models.Spec{
	Name:            "qwen3-coder-480b-a35b-instruct",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3CoderFlash is the Qwen3 Coder Flash model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3CoderFlash = models.Spec{
	Name:            "qwen3-coder-flash",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3CoderPlus is the Qwen3 Coder Plus model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3CoderPlus = models.Spec{
	Name:            "qwen3-coder-plus",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3LivetranslateFlashRealtime is the Qwen3-LiveTranslate Flash Realtime model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3LivetranslateFlashRealtime = models.Spec{
	Name:            "qwen3-livetranslate-flash-realtime",
	Window:          53248,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Max is the Qwen3 Max model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3Max = models.Spec{
	Name:            "qwen3-max",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Next80bA3bInstruct is the Qwen3-Next 80B-A3B Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3Next80bA3bInstruct = models.Spec{
	Name:            "qwen3-next-80b-a3b-instruct",
	Window:          131072,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Next80bA3bThinking is the Qwen3-Next 80B-A3B (Thinking) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3Next80bA3bThinking = models.Spec{
	Name:            "qwen3-next-80b-a3b-thinking",
	Window:          131072,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3OmniFlash is the Qwen3-Omni Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3OmniFlash = models.Spec{
	Name:            "qwen3-omni-flash",
	Window:          65536,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3OmniFlashRealtime is the Qwen3-Omni Flash Realtime model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Qwen3OmniFlashRealtime = models.Spec{
	Name:            "qwen3-omni-flash-realtime",
	Window:          65536,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Qwen3Vl235bA22b is the Qwen3-VL 235B-A22B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3Vl235bA22b = models.Spec{
	Name:            "qwen3-vl-235b-a22b",
	Window:          131072,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3Vl30bA3b is the Qwen3-VL 30B-A3B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3Vl30bA3b = models.Spec{
	Name:            "qwen3-vl-30b-a3b",
	Window:          131072,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3VlPlus is the Qwen3-VL Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3VlPlus = models.Spec{
	Name:            "qwen3-vl-plus",
	Window:          262144,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen35122bA10b is the Qwen3.5 122B-A10B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen35122bA10b = models.Spec{
	Name:            "qwen3.5-122b-a10b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3527b is the Qwen3.5 27B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3527b = models.Spec{
	Name:            "qwen3.5-27b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3535bA3b is the Qwen3.5 35B-A3B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3535bA3b = models.Spec{
	Name:            "qwen3.5-35b-a3b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen35397bA17b is the Qwen3.5 397B-A17B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen35397bA17b = models.Spec{
	Name:            "qwen3.5-397b-a17b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen35Plus is the Qwen3.5 Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen35Plus = models.Spec{
	Name:            "qwen3.5-plus",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3627b is the Qwen3.6 27B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3627b = models.Spec{
	Name:            "qwen3.6-27b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen3635bA3b is the Qwen3.6 35B-A3B model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen3635bA3b = models.Spec{
	Name:            "qwen3.6-35b-a3b",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen36Flash is the Qwen3.6 Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen36Flash = models.Spec{
	Name:            "qwen3.6-flash",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen36MaxPreview is the Qwen3.6 Max Preview model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen36MaxPreview = models.Spec{
	Name:            "qwen3.6-max-preview",
	Window:          262144,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen36Plus is the Qwen3.6 Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen36Plus = models.Spec{
	Name:            "qwen3.6-plus",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen37Max is the Qwen3.7 Max model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen37Max = models.Spec{
	Name:            "qwen3.7-max",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Qwen37Plus is the Qwen3.7 Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Qwen37Plus = models.Spec{
	Name:            "qwen3.7-plus",
	Window:          1000000,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// QwqPlus is the QwQ Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var QwqPlus = models.Spec{
	Name:            "qwq-plus",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
