// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the anthropic family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// Claude35Haiku20241022 is the Claude Haiku 3.5 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude35Haiku20241022 = models.Spec{
	Name:            "claude-3-5-haiku-20241022",
	Window:          200000,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude35HaikuLatest is the Claude Haiku 3.5 (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude35HaikuLatest = models.Spec{
	Name:            "claude-3-5-haiku-latest",
	Window:          200000,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude35Sonnet20240620 is the Claude Sonnet 3.5 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude35Sonnet20240620 = models.Spec{
	Name:            "claude-3-5-sonnet-20240620",
	Window:          200000,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude35Sonnet20241022 is the Claude Sonnet 3.5 v2 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude35Sonnet20241022 = models.Spec{
	Name:            "claude-3-5-sonnet-20241022",
	Window:          200000,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude37Sonnet20250219 is the Claude Sonnet 3.7 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Claude37Sonnet20250219 = models.Spec{
	Name:            "claude-3-7-sonnet-20250219",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Claude3Haiku20240307 is the Claude Haiku 3 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude3Haiku20240307 = models.Spec{
	Name:            "claude-3-haiku-20240307",
	Window:          200000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude3Opus20240229 is the Claude Opus 3 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude3Opus20240229 = models.Spec{
	Name:            "claude-3-opus-20240229",
	Window:          200000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Claude3Sonnet20240229 is the Claude Sonnet 3 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Claude3Sonnet20240229 = models.Spec{
	Name:            "claude-3-sonnet-20240229",
	Window:          200000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// ClaudeFable5 is the Claude Fable 5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeFable5 = models.Spec{
	Name:            "claude-fable-5",
	Window:          1000000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeHaiku45 is the Claude Haiku 4.5 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeHaiku45 = models.Spec{
	Name:            "claude-haiku-4-5",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeHaiku4520251001 is the Claude Haiku 4.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeHaiku4520251001 = models.Spec{
	Name:            "claude-haiku-4-5-20251001",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus40 is the Claude Opus 4 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus40 = models.Spec{
	Name:            "claude-opus-4-0",
	Window:          200000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus41 is the Claude Opus 4.1 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus41 = models.Spec{
	Name:            "claude-opus-4-1",
	Window:          200000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus4120250805 is the Claude Opus 4.1 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus4120250805 = models.Spec{
	Name:            "claude-opus-4-1-20250805",
	Window:          200000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus420250514 is the Claude Opus 4 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus420250514 = models.Spec{
	Name:            "claude-opus-4-20250514",
	Window:          200000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus45 is the Claude Opus 4.5 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus45 = models.Spec{
	Name:            "claude-opus-4-5",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus4520251101 is the Claude Opus 4.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus4520251101 = models.Spec{
	Name:            "claude-opus-4-5-20251101",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus46 is the Claude Opus 4.6 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus46 = models.Spec{
	Name:            "claude-opus-4-6",
	Window:          1000000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus47 is the Claude Opus 4.7 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus47 = models.Spec{
	Name:            "claude-opus-4-7",
	Window:          1000000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeOpus48 is the Claude Opus 4.8 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeOpus48 = models.Spec{
	Name:            "claude-opus-4-8",
	Window:          1000000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeSonnet40 is the Claude Sonnet 4 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeSonnet40 = models.Spec{
	Name:            "claude-sonnet-4-0",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeSonnet420250514 is the Claude Sonnet 4 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeSonnet420250514 = models.Spec{
	Name:            "claude-sonnet-4-20250514",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeSonnet45 is the Claude Sonnet 4.5 (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeSonnet45 = models.Spec{
	Name:            "claude-sonnet-4-5",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeSonnet4520250929 is the Claude Sonnet 4.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeSonnet4520250929 = models.Spec{
	Name:            "claude-sonnet-4-5-20250929",
	Window:          200000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// ClaudeSonnet46 is the Claude Sonnet 4.6 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var ClaudeSonnet46 = models.Spec{
	Name:            "claude-sonnet-4-6",
	Window:          1000000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
