// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the cohere family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// C4aiAyaExpanse32b is the Aya Expanse 32B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var C4aiAyaExpanse32b = models.Spec{
	Name:            "c4ai-aya-expanse-32b",
	Window:          128000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// C4aiAyaExpanse8b is the Aya Expanse 8B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var C4aiAyaExpanse8b = models.Spec{
	Name:            "c4ai-aya-expanse-8b",
	Window:          8000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// C4aiAyaVision32b is the Aya Vision 32B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var C4aiAyaVision32b = models.Spec{
	Name:            "c4ai-aya-vision-32b",
	Window:          16000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// C4aiAyaVision8b is the Aya Vision 8B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var C4aiAyaVision8b = models.Spec{
	Name:            "c4ai-aya-vision-8b",
	Window:          16000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandA032025 is the Command A model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandA032025 = models.Spec{
	Name:            "command-a-03-2025",
	Window:          256000,
	MaxOutputTokens: 8000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandAPlus052026 is the Command A Plus model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var CommandAPlus052026 = models.Spec{
	Name:            "command-a-plus-05-2026",
	Window:          128000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// CommandAReasoning082025 is the Command A Reasoning model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var CommandAReasoning082025 = models.Spec{
	Name:            "command-a-reasoning-08-2025",
	Window:          256000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// CommandATranslate082025 is the Command A Translate model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandATranslate082025 = models.Spec{
	Name:            "command-a-translate-08-2025",
	Window:          8000,
	MaxOutputTokens: 8000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandAVision072025 is the Command A Vision model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandAVision072025 = models.Spec{
	Name:            "command-a-vision-07-2025",
	Window:          128000,
	MaxOutputTokens: 8000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandR082024 is the Command R model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandR082024 = models.Spec{
	Name:            "command-r-08-2024",
	Window:          128000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandRPlus082024 is the Command R+ model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandRPlus082024 = models.Spec{
	Name:            "command-r-plus-08-2024",
	Window:          128000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandR7b122024 is the Command R7B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandR7b122024 = models.Spec{
	Name:            "command-r7b-12-2024",
	Window:          128000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CommandR7bArabic022025 is the Command R7B Arabic model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CommandR7bArabic022025 = models.Spec{
	Name:            "command-r7b-arabic-02-2025",
	Window:          128000,
	MaxOutputTokens: 4000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// NorthMiniCode10 is the North Mini Code model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var NorthMiniCode10 = models.Spec{
	Name:            "north-mini-code-1-0",
	Window:          256000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
