// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the deepseek family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// DeepseekChat is the DeepSeek Chat model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DeepseekChat = models.Spec{
	Name:            "deepseek-chat",
	Window:          1000000,
	MaxOutputTokens: 384000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DeepseekReasoner is the DeepSeek Reasoner model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var DeepseekReasoner = models.Spec{
	Name:            "deepseek-reasoner",
	Window:          1000000,
	MaxOutputTokens: 384000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// DeepseekV4Flash is the DeepSeek V4 Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var DeepseekV4Flash = models.Spec{
	Name:            "deepseek-v4-flash",
	Window:          1000000,
	MaxOutputTokens: 384000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// DeepseekV4Pro is the DeepSeek V4 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var DeepseekV4Pro = models.Spec{
	Name:            "deepseek-v4-pro",
	Window:          1000000,
	MaxOutputTokens: 384000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
