// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the google family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// Gemini20Flash is the Gemini 2.0 Flash model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gemini20Flash = models.Spec{
	Name:            "gemini-2.0-flash",
	Window:          1048576,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gemini20FlashLite is the Gemini 2.0 Flash-Lite model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gemini20FlashLite = models.Spec{
	Name:            "gemini-2.0-flash-lite",
	Window:          1048576,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gemini25Flash is the Gemini 2.5 Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini25Flash = models.Spec{
	Name:            "gemini-2.5-flash",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini25FlashImage is the Nano Banana model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini25FlashImage = models.Spec{
	Name:            "gemini-2.5-flash-image",
	Window:          32768,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini25FlashLite is the Gemini 2.5 Flash-Lite model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini25FlashLite = models.Spec{
	Name:            "gemini-2.5-flash-lite",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini25FlashPreviewTts is the Gemini 2.5 Flash Preview TTS model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gemini25FlashPreviewTts = models.Spec{
	Name:            "gemini-2.5-flash-preview-tts",
	Window:          8192,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gemini25Pro is the Gemini 2.5 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini25Pro = models.Spec{
	Name:            "gemini-2.5-pro",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini25ProPreviewTts is the Gemini 2.5 Pro Preview TTS model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gemini25ProPreviewTts = models.Spec{
	Name:            "gemini-2.5-pro-preview-tts",
	Window:          8192,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gemini3FlashPreview is the Gemini 3 Flash Preview model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini3FlashPreview = models.Spec{
	Name:            "gemini-3-flash-preview",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini3ProImagePreview is the Nano Banana Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini3ProImagePreview = models.Spec{
	Name:            "gemini-3-pro-image-preview",
	Window:          131072,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini3ProPreview is the Gemini 3 Pro Preview model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini3ProPreview = models.Spec{
	Name:            "gemini-3-pro-preview",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini31FlashImagePreview is the Nano Banana 2 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini31FlashImagePreview = models.Spec{
	Name:            "gemini-3.1-flash-image-preview",
	Window:          65536,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini31FlashLite is the Gemini 3.1 Flash Lite model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini31FlashLite = models.Spec{
	Name:            "gemini-3.1-flash-lite",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini31FlashLitePreview is the Gemini 3.1 Flash Lite Preview model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini31FlashLitePreview = models.Spec{
	Name:            "gemini-3.1-flash-lite-preview",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini31ProPreview is the Gemini 3.1 Pro Preview model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini31ProPreview = models.Spec{
	Name:            "gemini-3.1-pro-preview",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini31ProPreviewCustomtools is the Gemini 3.1 Pro Preview Custom Tools model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini31ProPreviewCustomtools = models.Spec{
	Name:            "gemini-3.1-pro-preview-customtools",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemini35Flash is the Gemini 3.5 Flash model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemini35Flash = models.Spec{
	Name:            "gemini-3.5-flash",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// GeminiEmbedding001 is the Gemini Embedding 001 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GeminiEmbedding001 = models.Spec{
	Name:            "gemini-embedding-001",
	Window:          2048,
	MaxOutputTokens: 1,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GeminiFlashLatest is the Gemini Flash Latest model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var GeminiFlashLatest = models.Spec{
	Name:            "gemini-flash-latest",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// GeminiFlashLiteLatest is the Gemini Flash-Lite Latest model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var GeminiFlashLiteLatest = models.Spec{
	Name:            "gemini-flash-lite-latest",
	Window:          1048576,
	MaxOutputTokens: 65536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemma426bA4bIt is the Gemma 4 26B A4B IT model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemma426bA4bIt = models.Spec{
	Name:            "gemma-4-26b-a4b-it",
	Window:          262144,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemma431bIt is the Gemma 4 31B IT model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemma431bIt = models.Spec{
	Name:            "gemma-4-31b-it",
	Window:          262144,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemma4E2BIt is the Gemma 4 E2B IT model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemma4E2BIt = models.Spec{
	Name:            "gemma-4-E2B-it",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gemma4E4BIt is the Gemma 4 E4B IT model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gemma4E4BIt = models.Spec{
	Name:            "gemma-4-E4B-it",
	Window:          131072,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
