// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the meta family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// CerebrasLlama4Maverick17b128eInstruct is the Cerebras-Llama-4-Maverick-17B-128E-Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CerebrasLlama4Maverick17b128eInstruct = models.Spec{
	Name:            "cerebras-llama-4-maverick-17b-128e-instruct",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// CerebrasLlama4Scout17b16eInstruct is the Cerebras-Llama-4-Scout-17B-16E-Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CerebrasLlama4Scout17b16eInstruct = models.Spec{
	Name:            "cerebras-llama-4-scout-17b-16e-instruct",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GroqLlama4Maverick17b128eInstruct is the Groq-Llama-4-Maverick-17B-128E-Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GroqLlama4Maverick17b128eInstruct = models.Spec{
	Name:            "groq-llama-4-maverick-17b-128e-instruct",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Llama3370bInstruct is the Llama-3.3-70B-Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Llama3370bInstruct = models.Spec{
	Name:            "llama-3.3-70b-instruct",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Llama338bInstruct is the Llama-3.3-8B-Instruct model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Llama338bInstruct = models.Spec{
	Name:            "llama-3.3-8b-instruct",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Llama4Maverick17b128eInstructFp8 is the Llama-4-Maverick-17B-128E-Instruct-FP8 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Llama4Maverick17b128eInstructFp8 = models.Spec{
	Name:            "llama-4-maverick-17b-128e-instruct-fp8",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Llama4Scout17b16eInstructFp8 is the Llama-4-Scout-17B-16E-Instruct-FP8 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Llama4Scout17b16eInstructFp8 = models.Spec{
	Name:            "llama-4-scout-17b-16e-instruct-fp8",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}
