// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the minimax family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// MiniMaxM2 is the MiniMax-M2 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM2 = models.Spec{
	Name:            "MiniMax-M2",
	Window:          196608,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM21 is the MiniMax-M2.1 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM21 = models.Spec{
	Name:            "MiniMax-M2.1",
	Window:          204800,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM25 is the MiniMax-M2.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM25 = models.Spec{
	Name:            "MiniMax-M2.5",
	Window:          204800,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM25Highspeed is the MiniMax-M2.5-highspeed model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM25Highspeed = models.Spec{
	Name:            "MiniMax-M2.5-highspeed",
	Window:          204800,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM27 is the MiniMax-M2.7 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM27 = models.Spec{
	Name:            "MiniMax-M2.7",
	Window:          204800,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM27Highspeed is the MiniMax-M2.7-highspeed model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM27Highspeed = models.Spec{
	Name:            "MiniMax-M2.7-highspeed",
	Window:          204800,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MiniMaxM3 is the MiniMax-M3 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MiniMaxM3 = models.Spec{
	Name:            "MiniMax-M3",
	Window:          512000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}
