// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the mistral family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// CodestralLatest is the Codestral (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var CodestralLatest = models.Spec{
	Name:            "codestral-latest",
	Window:          256000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Devstral2512 is the Devstral 2 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Devstral2512 = models.Spec{
	Name:            "devstral-2512",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DevstralLatest is the Devstral 2 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DevstralLatest = models.Spec{
	Name:            "devstral-latest",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DevstralMedium2507 is the Devstral Medium model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DevstralMedium2507 = models.Spec{
	Name:            "devstral-medium-2507",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DevstralMediumLatest is the Devstral 2 (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DevstralMediumLatest = models.Spec{
	Name:            "devstral-medium-latest",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DevstralSmall2505 is the Devstral Small 2505 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DevstralSmall2505 = models.Spec{
	Name:            "devstral-small-2505",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// DevstralSmall2507 is the Devstral Small model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var DevstralSmall2507 = models.Spec{
	Name:            "devstral-small-2507",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// LabsDevstralSmall2512 is the Devstral Small 2 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var LabsDevstralSmall2512 = models.Spec{
	Name:            "labs-devstral-small-2512",
	Window:          256000,
	MaxOutputTokens: 256000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MagistralMediumLatest is the Magistral Medium (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MagistralMediumLatest = models.Spec{
	Name:            "magistral-medium-latest",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MagistralSmall is the Magistral Small model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MagistralSmall = models.Spec{
	Name:            "magistral-small",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Ministral3bLatest is the Ministral 3B (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Ministral3bLatest = models.Spec{
	Name:            "ministral-3b-latest",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Ministral8bLatest is the Ministral 8B (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Ministral8bLatest = models.Spec{
	Name:            "ministral-8b-latest",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralEmbed is the Mistral Embed model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralEmbed = models.Spec{
	Name:            "mistral-embed",
	Window:          8000,
	MaxOutputTokens: 3072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralLarge2411 is the Mistral Large 2.1 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralLarge2411 = models.Spec{
	Name:            "mistral-large-2411",
	Window:          131072,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralLarge2512 is the Mistral Large 3 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralLarge2512 = models.Spec{
	Name:            "mistral-large-2512",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralLargeLatest is the Mistral Large (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralLargeLatest = models.Spec{
	Name:            "mistral-large-latest",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralMedium2505 is the Mistral Medium 3 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralMedium2505 = models.Spec{
	Name:            "mistral-medium-2505",
	Window:          131072,
	MaxOutputTokens: 131072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralMedium2508 is the Mistral Medium 3.1 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralMedium2508 = models.Spec{
	Name:            "mistral-medium-2508",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralMedium2604 is the Mistral Medium 3.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MistralMedium2604 = models.Spec{
	Name:            "mistral-medium-2604",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MistralMediumLatest is the Mistral Medium (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralMediumLatest = models.Spec{
	Name:            "mistral-medium-latest",
	Window:          262144,
	MaxOutputTokens: 262144,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralNemo is the Mistral Nemo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralNemo = models.Spec{
	Name:            "mistral-nemo",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralSmall2506 is the Mistral Small 3.2 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var MistralSmall2506 = models.Spec{
	Name:            "mistral-small-2506",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// MistralSmall2603 is the Mistral Small 4 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MistralSmall2603 = models.Spec{
	Name:            "mistral-small-2603",
	Window:          256000,
	MaxOutputTokens: 256000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// MistralSmallLatest is the Mistral Small (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var MistralSmallLatest = models.Spec{
	Name:            "mistral-small-latest",
	Window:          256000,
	MaxOutputTokens: 256000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// OpenMistral7b is the Mistral 7B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var OpenMistral7b = models.Spec{
	Name:            "open-mistral-7b",
	Window:          8000,
	MaxOutputTokens: 8000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// OpenMistralNemo is the Open Mistral Nemo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var OpenMistralNemo = models.Spec{
	Name:            "open-mistral-nemo",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// OpenMixtral8x22b is the Mixtral 8x22B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var OpenMixtral8x22b = models.Spec{
	Name:            "open-mixtral-8x22b",
	Window:          64000,
	MaxOutputTokens: 64000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// OpenMixtral8x7b is the Mixtral 8x7B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var OpenMixtral8x7b = models.Spec{
	Name:            "open-mixtral-8x7b",
	Window:          32000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Pixtral12b is the Pixtral 12B model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Pixtral12b = models.Spec{
	Name:            "pixtral-12b",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// PixtralLargeLatest is the Pixtral Large (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var PixtralLargeLatest = models.Spec{
	Name:            "pixtral-large-latest",
	Window:          128000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}
