// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the openai family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// ChatgptImageLatest is the chatgpt-image-latest model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var ChatgptImageLatest = models.Spec{
	Name:            "chatgpt-image-latest",
	Window:          0,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt35Turbo is the GPT-3.5-turbo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt35Turbo = models.Spec{
	Name:            "gpt-3.5-turbo",
	Window:          16385,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4 is the GPT-4 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4 = models.Spec{
	Name:            "gpt-4",
	Window:          8192,
	MaxOutputTokens: 8192,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4Turbo is the GPT-4 Turbo model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4Turbo = models.Spec{
	Name:            "gpt-4-turbo",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt41 is the GPT-4.1 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt41 = models.Spec{
	Name:            "gpt-4.1",
	Window:          1047576,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt41Mini is the GPT-4.1 mini model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt41Mini = models.Spec{
	Name:            "gpt-4.1-mini",
	Window:          1047576,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt41Nano is the GPT-4.1 nano model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt41Nano = models.Spec{
	Name:            "gpt-4.1-nano",
	Window:          1047576,
	MaxOutputTokens: 32768,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4o is the GPT-4o model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4o = models.Spec{
	Name:            "gpt-4o",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4o20240513 is the GPT-4o (2024-05-13) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4o20240513 = models.Spec{
	Name:            "gpt-4o-2024-05-13",
	Window:          128000,
	MaxOutputTokens: 4096,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4o20240806 is the GPT-4o (2024-08-06) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4o20240806 = models.Spec{
	Name:            "gpt-4o-2024-08-06",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4o20241120 is the GPT-4o (2024-11-20) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4o20241120 = models.Spec{
	Name:            "gpt-4o-2024-11-20",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt4oMini is the GPT-4o mini model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt4oMini = models.Spec{
	Name:            "gpt-4o-mini",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt5 is the GPT-5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5 = models.Spec{
	Name:            "gpt-5",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt5ChatLatest is the GPT-5 Chat (latest) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5ChatLatest = models.Spec{
	Name:            "gpt-5-chat-latest",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt5Codex is the GPT-5-Codex model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5Codex = models.Spec{
	Name:            "gpt-5-codex",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt5Mini is the GPT-5 Mini model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5Mini = models.Spec{
	Name:            "gpt-5-mini",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt5Nano is the GPT-5 Nano model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5Nano = models.Spec{
	Name:            "gpt-5-nano",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt5Pro is the GPT-5 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt5Pro = models.Spec{
	Name:            "gpt-5-pro",
	Window:          400000,
	MaxOutputTokens: 272000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt51 is the GPT-5.1 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt51 = models.Spec{
	Name:            "gpt-5.1",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt51ChatLatest is the GPT-5.1 Chat model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt51ChatLatest = models.Spec{
	Name:            "gpt-5.1-chat-latest",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt51Codex is the GPT-5.1 Codex model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt51Codex = models.Spec{
	Name:            "gpt-5.1-codex",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt51CodexMax is the GPT-5.1 Codex Max model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt51CodexMax = models.Spec{
	Name:            "gpt-5.1-codex-max",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt51CodexMini is the GPT-5.1 Codex mini model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt51CodexMini = models.Spec{
	Name:            "gpt-5.1-codex-mini",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt52 is the GPT-5.2 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt52 = models.Spec{
	Name:            "gpt-5.2",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt52ChatLatest is the GPT-5.2 Chat model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt52ChatLatest = models.Spec{
	Name:            "gpt-5.2-chat-latest",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt52Codex is the GPT-5.2 Codex model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt52Codex = models.Spec{
	Name:            "gpt-5.2-codex",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt52Pro is the GPT-5.2 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt52Pro = models.Spec{
	Name:            "gpt-5.2-pro",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt53ChatLatest is the GPT-5.3 Chat (latest) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Gpt53ChatLatest = models.Spec{
	Name:            "gpt-5.3-chat-latest",
	Window:          128000,
	MaxOutputTokens: 16384,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Gpt53Codex is the GPT-5.3 Codex model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt53Codex = models.Spec{
	Name:            "gpt-5.3-codex",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt53CodexSpark is the GPT-5.3 Codex Spark model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt53CodexSpark = models.Spec{
	Name:            "gpt-5.3-codex-spark",
	Window:          128000,
	MaxOutputTokens: 32000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt54 is the GPT-5.4 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt54 = models.Spec{
	Name:            "gpt-5.4",
	Window:          1050000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt54Mini is the GPT-5.4 mini model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt54Mini = models.Spec{
	Name:            "gpt-5.4-mini",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt54Nano is the GPT-5.4 nano model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt54Nano = models.Spec{
	Name:            "gpt-5.4-nano",
	Window:          400000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt54Pro is the GPT-5.4 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt54Pro = models.Spec{
	Name:            "gpt-5.4-pro",
	Window:          1050000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt55 is the GPT-5.5 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt55 = models.Spec{
	Name:            "gpt-5.5",
	Window:          1050000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Gpt55Pro is the GPT-5.5 Pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Gpt55Pro = models.Spec{
	Name:            "gpt-5.5-pro",
	Window:          1050000,
	MaxOutputTokens: 128000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// GptImage1 is the gpt-image-1 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GptImage1 = models.Spec{
	Name:            "gpt-image-1",
	Window:          0,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GptImage1Mini is the gpt-image-1-mini model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GptImage1Mini = models.Spec{
	Name:            "gpt-image-1-mini",
	Window:          0,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GptImage15 is the gpt-image-1.5 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GptImage15 = models.Spec{
	Name:            "gpt-image-1.5",
	Window:          0,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// O1 is the o1 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O1 = models.Spec{
	Name:            "o1",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O1Pro is the o1-pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O1Pro = models.Spec{
	Name:            "o1-pro",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O3 is the o3 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O3 = models.Spec{
	Name:            "o3",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O3DeepResearch is the o3-deep-research model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O3DeepResearch = models.Spec{
	Name:            "o3-deep-research",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O3Mini is the o3-mini model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O3Mini = models.Spec{
	Name:            "o3-mini",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O3Pro is the o3-pro model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O3Pro = models.Spec{
	Name:            "o3-pro",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O4Mini is the o4-mini model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O4Mini = models.Spec{
	Name:            "o4-mini",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// O4MiniDeepResearch is the o4-mini-deep-research model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var O4MiniDeepResearch = models.Spec{
	Name:            "o4-mini-deep-research",
	Window:          200000,
	MaxOutputTokens: 100000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// TextEmbedding3Large is the text-embedding-3-large model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var TextEmbedding3Large = models.Spec{
	Name:            "text-embedding-3-large",
	Window:          8191,
	MaxOutputTokens: 3072,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// TextEmbedding3Small is the text-embedding-3-small model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var TextEmbedding3Small = models.Spec{
	Name:            "text-embedding-3-small",
	Window:          8191,
	MaxOutputTokens: 1536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// TextEmbeddingAda002 is the text-embedding-ada-002 model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var TextEmbeddingAda002 = models.Spec{
	Name:            "text-embedding-ada-002",
	Window:          8192,
	MaxOutputTokens: 1536,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}
