// Code generated by cmd/modelsdev-gen. DO NOT EDIT.
//
// Source: https://models.dev (regenerated when the upstream catalog
// changes). Models here are the well-known [models.Spec] values for
// the xai family. The Name field is the canonical wire
// name understood by the upstream primary's API.
//
// The catalog is generated; do not hand-edit these values. To add
// a new family, edit cmd/modelsdev-gen/main.go and re-run the
// generator.
package catalogmodels

import "github.com/andrewhowdencom/ore/models"

// Grok4200309NonReasoning is the Grok 4.20 (Non-Reasoning) model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var Grok4200309NonReasoning = models.Spec{
	Name:            "grok-4.20-0309-non-reasoning",
	Window:          1000000,
	MaxOutputTokens: 30000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// Grok4200309Reasoning is the Grok 4.20 (Reasoning) model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Grok4200309Reasoning = models.Spec{
	Name:            "grok-4.20-0309-reasoning",
	Window:          1000000,
	MaxOutputTokens: 30000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Grok420MultiAgent0309 is the Grok 4.20 Multi-Agent model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Grok420MultiAgent0309 = models.Spec{
	Name:            "grok-4.20-multi-agent-0309",
	Window:          1000000,
	MaxOutputTokens: 30000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// Grok43 is the Grok 4.3 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var Grok43 = models.Spec{
	Name:            "grok-4.3",
	Window:          1000000,
	MaxOutputTokens: 30000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// GrokBuild01 is the Grok Build 0.1 model. It
// is a reasoning model; the spec's ThinkingLevel is set to medium
// so callers get reasoning by default.
//
// Source: https://models.dev/api.json
var GrokBuild01 = models.Spec{
	Name:            "grok-build-0.1",
	Window:          256000,
	MaxOutputTokens: 256000,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelMedium,
}

// GrokImagineImage is the Grok Imagine Image model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GrokImagineImage = models.Spec{
	Name:            "grok-imagine-image",
	Window:          8000,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GrokImagineImageQuality is the Grok Imagine Image Quality model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GrokImagineImageQuality = models.Spec{
	Name:            "grok-imagine-image-quality",
	Window:          8000,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}

// GrokImagineVideo is the Grok Imagine Video model. The spec's
// ThinkingLevel is set to off; callers that want reasoning must
// override per-call.
//
// Source: https://models.dev/api.json
var GrokImagineVideo = models.Spec{
	Name:            "grok-imagine-video",
	Window:          1024,
	MaxOutputTokens: 0,
	Temperature:     ptr(1.0),
	ThinkingLevel:   models.ThinkingLevelOff,
}
